### ISSUE TITLE
你好 运行出错 ？ 希望指点

### ISSUE THREAD

**Issue by xinxiwu** [chengjoey/web-terminal#1]
E:\gogo\src\github.com\chengjoey\web-terminal>go build .
..\..\gin-gonic\gin\binding\protobuf.go:11:2: cannot find package "github.com/golang/protobuf/proto" in any of:
        D:\dev\Go\src\github.com\golang\protobuf\proto (from $GOROOT)
        E:\gogo\src\github.com\golang\protobuf\proto (from $GOPATH)
..\..\gin-gonic\gin\logger.go:14:2: cannot find package "github.com/mattn/go-isatty" in any of:
        D:\dev\Go\src\github.com\mattn\go-isatty (from $GOROOT)
        E:\gogo\src\github.com\mattn\go-isatty (from $GOPATH)
..\..\gin-gonic\gin\binding\msgpack.go:14:2: cannot find package "github.com/ugorji/go/codec" in any of:
        D:\dev\Go\src\github.com\ugorji\go\codec (from $GOROOT)
        E:\gogo\src\github.com\ugorji\go\codec (from $GOPATH)
connections\funcs.go:14:2: cannot find package "golang.org/x/crypto/ssh" in any of:
        D:\dev\Go\src\golang.org\x\crypto\ssh (from $GOROOT)
        E:\gogo\src\golang.org\x\crypto\ssh (from $GOPATH)
..\..\gin-gonic\gin\binding\yaml.go:12:2: cannot find package "gopkg.in/yaml.v2" in any of:
        D:\dev\Go\src\gopkg.in\yaml.v2 (from $GOROOT)
        E:\gogo\src\gopkg.in\yaml.v2 (from $GOPATH)

E:\gogo\src\github.com\chengjoey\web-terminal>

**Comment by chengjoey** [comment]
> E:\gogo\src\github.com\chengjoey\web-terminal>go build .
> ....\gin-gonic\gin\binding\protobuf.go:11:2: cannot find package "github.com/golang/protobuf/proto" in any of:
> D:\dev\Go\src\github.com\golang\protobuf\proto (from $GOROOT)
> E:\gogo\src\github.com\golang\protobuf\proto (from $GOPATH)
> ....\gin-gonic\gin\logger.go:14:2: cannot find package "github.com/mattn/go-isatty" in any of:
> D:\dev\Go\src\github.com\mattn\go-isatty (from $GOROOT)
> E:\gogo\src\github.com\mattn\go-isatty (from $GOPATH)
> ....\gin-gonic\gin\binding\msgpack.go:14:2: cannot find package "github.com/ugorji/go/codec" in any of:
> D:\dev\Go\src\github.com\ugorji\go\codec (from $GOROOT)
> E:\gogo\src\github.com\ugorji\go\codec (from $GOPATH)
> connections\funcs.go:14:2: cannot find package "golang.org/x/crypto/ssh" in any of:
> D:\dev\Go\src\golang.org\x\crypto\ssh (from $GOROOT)
> E:\gogo\src\golang.org\x\crypto\ssh (from $GOPATH)
> ....\gin-gonic\gin\binding\yaml.go:12:2: cannot find package "gopkg.in/yaml.v2" in any of:
> D:\dev\Go\src\gopkg.in\yaml.v2 (from $GOROOT)
> E:\gogo\src\gopkg.in\yaml.v2 (from $GOPATH)
> 
> E:\gogo\src\github.com\chengjoey\web-terminal>

可以将`go env`的输出结果看一下吗,或许是go环境问题

**Comment by xinxiwu** [comment]
C:\Users\sushuai>go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sushuai\AppData\Local\go-build
set GOENV=C:\Users\sushuai\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\gogo
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=D:\dev\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\dev\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\sushuai\AppData\Local\Temp\go-build445750362=/tmp/go-build -gno-record-gcc-switches

C:\Users\sushuai>

**Comment by chengjoey** [comment]
> C:\Users\sushuai>go env
> set GO111MODULE=
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\sushuai\AppData\Local\go-build
> set GOENV=C:\Users\sushuai\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=E:\gogo
> set GOPRIVATE=
> set GOPROXY=https://goproxy.cn
> set GOROOT=D:\dev\Go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=D:\dev\Go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\sushuai\AppData\Local\Temp\go-build445750362=/tmp/go-build -gno-record-gcc-switches
> 
> C:\Users\sushuai>

你是用`go get`安装的包吗,还是git clone? 看上面的报错是缺少包的原因,你可以试着将缺失的包go get一下,我在晚点的时候上传mod包管理文件

**Comment by xinxiwu** [comment]
go get 下载好像很慢，2好 你上传mod包管理文件

**Comment by chengjoey** [comment]
> go get 下载好像很慢，2好 你上传mod包管理文件

已上传mod管理文件, 但是解决不了你的问题, 还是用go get吧, 不然会缺少依赖包的, 有些包可能很慢, 最好翻墙使用代理下载

**Comment by xinxiwu** [comment]
> > go get 下载好像很慢，2好 你上传mod包管理文件
> 
> 已上传mod管理文件, 但是解决不了你的问题, 还是用go get吧, 不然会缺少依赖包的, 有些包可能很慢, 最好翻墙使用代理下载
使用的什么翻墙软件，我找一下

**Comment by chengjoey** [comment]
> > > go get 下载好像很慢，2好 你上传mod包管理文件
> > 
> > 
> > 已上传mod管理文件, 但是解决不了你的问题, 还是用go get吧, 不然会缺少依赖包的, 有些包可能很慢, 最好翻墙使用代理下载
> > 使用的什么翻墙软件，我找一下

我用的v2ray, 但是需要有自己的服务器, 然后需要v2ray开启http代理
